//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketManagementWPF.l10n.Map {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Hints {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Hints() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketManagementWPF.l10n.Map.Hints", typeof(Hints).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press left mouse button in order to add an area.
        /// </summary>
        internal static string AddArea {
            get {
                return ResourceManager.GetString("AddArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press left mouse button in order to add a seat.
        /// </summary>
        internal static string AddSeat {
            get {
                return ResourceManager.GetString("AddSeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press right mouse button in order to delete an area.
        /// </summary>
        internal static string DeleteArea {
            get {
                return ResourceManager.GetString("DeleteArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press left mouse button in order to delete a seat.
        /// </summary>
        internal static string DeleteSeat {
            get {
                return ResourceManager.GetString("DeleteSeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click left mouse  button on cell in order to edit an area .
        /// </summary>
        internal static string EditArea {
            get {
                return ResourceManager.GetString("EditArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use mouse to move item.
        /// </summary>
        internal static string ItemMove {
            get {
                return ResourceManager.GetString("ItemMove", resourceCulture);
            }
        }
    }
}
