//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketManagementMVC.EventAreaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EventAreaService.IWcfEventAreaService")]
    public interface IWcfEventAreaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfEventAreaService/Create", ReplyAction="http://tempuri.org/IWcfEventAreaService/CreateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfBusinessLogic.Core.Contracts.Exceptions.ServiceValidationFaultDetails), Action="http://tempuri.org/IWcfEventAreaService/CreateServiceValidationFaultDetailsFault", Name="ServiceValidationFaultDetails", Namespace="http://schemas.datacontract.org/2004/07/WcfBusinessLogic.Core.Contracts.Exception" +
            "s")]
        int Create(WcfBusinessLogic.Core.Contracts.Data.EventArea entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfEventAreaService/Create", ReplyAction="http://tempuri.org/IWcfEventAreaService/CreateResponse")]
        System.Threading.Tasks.Task<int> CreateAsync(WcfBusinessLogic.Core.Contracts.Data.EventArea entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfEventAreaService/Update", ReplyAction="http://tempuri.org/IWcfEventAreaService/UpdateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfBusinessLogic.Core.Contracts.Exceptions.ServiceValidationFaultDetails), Action="http://tempuri.org/IWcfEventAreaService/UpdateServiceValidationFaultDetailsFault", Name="ServiceValidationFaultDetails", Namespace="http://schemas.datacontract.org/2004/07/WcfBusinessLogic.Core.Contracts.Exception" +
            "s")]
        void Update(WcfBusinessLogic.Core.Contracts.Data.EventArea entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfEventAreaService/Update", ReplyAction="http://tempuri.org/IWcfEventAreaService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(WcfBusinessLogic.Core.Contracts.Data.EventArea entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfEventAreaService/Delete", ReplyAction="http://tempuri.org/IWcfEventAreaService/DeleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfBusinessLogic.Core.Contracts.Exceptions.ServiceValidationFaultDetails), Action="http://tempuri.org/IWcfEventAreaService/DeleteServiceValidationFaultDetailsFault", Name="ServiceValidationFaultDetails", Namespace="http://schemas.datacontract.org/2004/07/WcfBusinessLogic.Core.Contracts.Exception" +
            "s")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfEventAreaService/Delete", ReplyAction="http://tempuri.org/IWcfEventAreaService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfEventAreaService/Get", ReplyAction="http://tempuri.org/IWcfEventAreaService/GetResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfBusinessLogic.Core.Contracts.Exceptions.ServiceValidationFaultDetails), Action="http://tempuri.org/IWcfEventAreaService/GetServiceValidationFaultDetailsFault", Name="ServiceValidationFaultDetails", Namespace="http://schemas.datacontract.org/2004/07/WcfBusinessLogic.Core.Contracts.Exception" +
            "s")]
        WcfBusinessLogic.Core.Contracts.Data.EventArea Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfEventAreaService/Get", ReplyAction="http://tempuri.org/IWcfEventAreaService/GetResponse")]
        System.Threading.Tasks.Task<WcfBusinessLogic.Core.Contracts.Data.EventArea> GetAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfEventAreaServiceChannel : TicketManagementMVC.EventAreaService.IWcfEventAreaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfEventAreaServiceClient : System.ServiceModel.ClientBase<TicketManagementMVC.EventAreaService.IWcfEventAreaService>, TicketManagementMVC.EventAreaService.IWcfEventAreaService {
        
        public WcfEventAreaServiceClient() {
        }
        
        public WcfEventAreaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfEventAreaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfEventAreaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfEventAreaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Create(WcfBusinessLogic.Core.Contracts.Data.EventArea entity) {
            return base.Channel.Create(entity);
        }
        
        public System.Threading.Tasks.Task<int> CreateAsync(WcfBusinessLogic.Core.Contracts.Data.EventArea entity) {
            return base.Channel.CreateAsync(entity);
        }
        
        public void Update(WcfBusinessLogic.Core.Contracts.Data.EventArea entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(WcfBusinessLogic.Core.Contracts.Data.EventArea entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public WcfBusinessLogic.Core.Contracts.Data.EventArea Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<WcfBusinessLogic.Core.Contracts.Data.EventArea> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
    }
}
