//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EventResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EventResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketManagementMVC.App_GlobalResources.event.EventResource", typeof(EventResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area list.
        /// </summary>
        public static string AreaList {
            get {
                return ResourceManager.GetString("AreaList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coord X - Coord Y.
        /// </summary>
        public static string CoordsXY {
            get {
                return ResourceManager.GetString("CoordsXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coord X.
        /// </summary>
        public static string CoordX {
            get {
                return ResourceManager.GetString("CoordX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coord Y.
        /// </summary>
        public static string CoordY {
            get {
                return ResourceManager.GetString("CoordY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create area.
        /// </summary>
        public static string CreateArea {
            get {
                return ResourceManager.GetString("CreateArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit area.
        /// </summary>
        public static string EditArea {
            get {
                return ResourceManager.GetString("EditArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select event to edit.
        /// </summary>
        public static string EditEventSelectDropDown {
            get {
                return ResourceManager.GetString("EditEventSelectDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1} at {2}.
        /// </summary>
        public static string EventDispalyInformation {
            get {
                return ResourceManager.GetString("EventDispalyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event information.
        /// </summary>
        public static string EventInformation {
            get {
                return ResourceManager.GetString("EventInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: {0}, {1}.
        /// </summary>
        public static string EventListDate {
            get {
                return ResourceManager.GetString("EventListDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event list.
        /// </summary>
        public static string EventListTitle {
            get {
                return ResourceManager.GetString("EventListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is on {0}.
        /// </summary>
        public static string EventListVenue {
            get {
                return ResourceManager.GetString("EventListVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select venue.
        /// </summary>
        public static string EventSelectVenueDropDownLabel {
            get {
                return ResourceManager.GetString("EventSelectVenueDropDownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event is on {0}, {1}.
        /// </summary>
        public static string EventVenue {
            get {
                return ResourceManager.GetString("EventVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select layout.
        /// </summary>
        public static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage event.
        /// </summary>
        public static string ManageEvent {
            get {
                return ResourceManager.GetString("ManageEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select filter.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price, USD.
        /// </summary>
        public static string PriceCurrency {
            get {
                return ResourceManager.GetString("PriceCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string PurchasedSeatCounter {
            get {
                return ResourceManager.GetString("PurchasedSeatCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene.
        /// </summary>
        public static string Scene {
            get {
                return ResourceManager.GetString("Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat list.
        /// </summary>
        public static string SeatList {
            get {
                return ResourceManager.GetString("SeatList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat number.
        /// </summary>
        public static string SeatNumber {
            get {
                return ResourceManager.GetString("SeatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat row.
        /// </summary>
        public static string SeatRow {
            get {
                return ResourceManager.GetString("SeatRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat(row-num).
        /// </summary>
        public static string SeatRowNum {
            get {
                return ResourceManager.GetString("SeatRowNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string SeatState {
            get {
                return ResourceManager.GetString("SeatState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image.
        /// </summary>
        public static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue (Hall).
        /// </summary>
        public static string VenueWithLayout {
            get {
                return ResourceManager.GetString("VenueWithLayout", resourceCulture);
            }
        }
    }
}
