CREATE TABLE [dbo].[Order]
(
	[Id] INT IDENTITY PRIMARY KEY, 
    [UserId] INT NOT NULL, 
    [Date] DATETIMEOFFSET NOT NULL, 
    CONSTRAINT [FK_Order_User] FOREIGN KEY ([UserId]) REFERENCES [User]([Id])
)
