CREATE TABLE [dbo].[Order]
(
	[Id] INT IDENTITY PRIMARY KEY, 
    [UserId] NVARCHAR(128) NOT NULL, 
    [Date] DATETIME NOT NULL, 
    CONSTRAINT [FK_Order_User] FOREIGN KEY ([UserId]) REFERENCES [User]([Id])
)
