//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketManagementWPF.l10n.VenueView {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketManagementWPF.l10n.VenueView.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area description must be unique within the layout.
        /// </summary>
        public static string AreaDescriptionUnique {
            get {
                return ResourceManager.GetString("AreaDescriptionUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some area has no seats.
        /// </summary>
        public static string AreaHasNoSeats {
            get {
                return ResourceManager.GetString("AreaHasNoSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout description must be unique within the venue.
        /// </summary>
        public static string LayoutDescriptionUnique {
            get {
                return ResourceManager.GetString("LayoutDescriptionUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some layout has no areas.
        /// </summary>
        public static string LayoutHasNoArea {
            get {
                return ResourceManager.GetString("LayoutHasNoArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed to delete. Venue has contains events.
        /// </summary>
        public static string VenueDelete {
            get {
                return ResourceManager.GetString("VenueDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect state of the venue. The venue must have at least one layout.
        /// </summary>
        public static string VenueHasNoLayouts {
            get {
                return ResourceManager.GetString("VenueHasNoLayouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue name must be unique.
        /// </summary>
        public static string VenueNameIsExists {
            get {
                return ResourceManager.GetString("VenueNameIsExists", resourceCulture);
            }
        }
    }
}
