//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketManagementMVC.App_GlobalResources.ResourceErrors", typeof(ResourceErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is not unique. Descrription have to be unique within event.
        /// </summary>
        public static string AreaDescriptionError {
            get {
                return ResourceManager.GetString("AreaDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is not valid.
        /// </summary>
        public static string ChangePasswordError {
            get {
                return ResourceManager.GetString("ChangePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match.
        /// </summary>
        public static string ConfirmPasswordError {
            get {
                return ResourceManager.GetString("ConfirmPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is not valid or was not entered.
        /// </summary>
        public static string DateValidation {
            get {
                return ResourceManager.GetString("DateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed to delete event. Event has locked seats.
        /// </summary>
        public static string DeleteEventError {
            get {
                return ResourceManager.GetString("DeleteEventError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid.
        /// </summary>
        public static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with this email has been already created.
        /// </summary>
        public static string EmalIsTaken {
            get {
                return ResourceManager.GetString("EmalIsTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some event already created at the selected layout in picked time.
        /// </summary>
        public static string EventInvalidDateError {
            get {
                return ResourceManager.GetString("EventInvalidDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed to change layout of event. Event has locked seats.
        /// </summary>
        public static string EventLayoutChangeError {
            get {
                return ResourceManager.GetString("EventLayoutChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is not valid.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For field {0} only characters are allowed.
        /// </summary>
        public static string NumericError {
            get {
                return ResourceManager.GetString("NumericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The balance is less than order amount.
        /// </summary>
        public static string OrderError {
            get {
                return ResourceManager.GetString("OrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must has at least 10 characters.
        /// </summary>
        public static string PassworkdRangeError {
            get {
                return ResourceManager.GetString("PassworkdRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt of creating of the event in the past.
        /// </summary>
        public static string PastDateError {
            get {
                return ResourceManager.GetString("PastDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string PropertyRequired {
            get {
                return ResourceManager.GetString("PropertyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such seat already exists within current area.
        /// </summary>
        public static string SeatExistsError {
            get {
                return ResourceManager.GetString("SeatExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat list is empty. The area has to has atleast one seat.
        /// </summary>
        public static string SeatListError {
            get {
                return ResourceManager.GetString("SeatListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat already locked.
        /// </summary>
        public static string SeatLocked {
            get {
                return ResourceManager.GetString("SeatLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected area has locked or purchaced seats.
        /// </summary>
        public static string SeatLockedError {
            get {
                return ResourceManager.GetString("SeatLockedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat number or seat row were not entered.
        /// </summary>
        public static string SeatValdiatation {
            get {
                return ResourceManager.GetString("SeatValdiatation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time is not valid or was not entered.
        /// </summary>
        public static string TimeValidation {
            get {
                return ResourceManager.GetString("TimeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username is already taken.
        /// </summary>
        public static string UserNameIsTaken {
            get {
                return ResourceManager.GetString("UserNameIsTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency value is not valid.
        /// </summary>
        public static string ValidateDecimal {
            get {
                return ResourceManager.GetString("ValidateDecimal", resourceCulture);
            }
        }
    }
}
